/**:
  ros_parameters:
    biguasim_scenario:
      package_name: SkyDive
      world: Pier-Harbor
      main_agent: auv0     
      ticks_per_sec: 30
      frames_per_sec: 180
      octree_min: 0.1
      octree_max: 5
      draw_arrow: true
      show_viewport: true
      agents:
        - agent_name: auv0
          agent_type: BlueROV2
          publish_commands: false
          sensors:
            - sensor_type: DynamicsSensor
              ros_publish: true
              configuration:
                UseCOM: true
                UseRPY: false
            - sensor_type: LocationSensor
              ros_publish: true
            - sensor_type: RotationSensor
              ros_publish: true
            - sensor_type: VelocitySensor
              ros_publish: true
          dynamics:
            batch_size : 5
          control_abstraction : 'cmd_motor_speeds'
          location: [10, -301, -1]
          rotation: [0, 0, 0]
        - agent_name: auv1
          agent_type: BlueROV2
          publish_commands: false
          sensors:
            - sensor_type: DynamicsSensor
              ros_publish: true
              configuration:
                UseCOM: true
                UseRPY: false
            - sensor_type: ImagingSonar
              ros_publish: true
              configuration:
                RangeBins: 64
                AzimuthBins: 64
                RangeMin: 0
                RangeMax: 40
                InitOctreeRange: 20
                Elevation: 28
                Azimuth: 28.8
                AzimuthStreaks: -1
                ScaleNoise: true
                AddSigma: 0.15
                MultSigma: 0.2
                RangeSigma: 0.0
                MultiPath: true
                ViewRegion: true
                ViewOctree: -1
                # SendGTElevation: true
                # SendGTIntensity: true
                SendGTPointCloud: true
          dynamics:
            batch_size : 1
          control_abstraction : 'cmd_motor_speeds'
          location: [10, -303, -1]
          rotation: [0, 0, 0]

          
          