[General]

[UdpEndpoint qgc]
Mode = Normal
Address = 127.0.0.1
Port = 14550

[UdpEndpoint ros2]
Mode = Normal
Address = 127.0.0.1
Port = 18540
[UdpEndpoint drone1]
Mode = Eavesdropping
Address = 0.0.0.0
Port = 16540
