/**:
  ros_parameters:
    holoocean_scenario:
      name: hovering_dynamics
      package_name: Tank
      world: 64-tank-Map-1
      main_agent: auv0     
      ticks_per_sec: 30
      frames_per_sec: 180
      octree_min: 0.1
      octree_max: 5
      draw_arrow: true
      show_viewport: true
      agents:
        - agent_name: auv0
          agent_type: BlueROV2
          control_scheme: 0  
          location: [0, -50, -10]
          rotation: [0, 0, 90]
          publish_commands: false
          sensors:
            - sensor_type: DVLSensor
              ros_publish: true
              tick_every: 3
              configuration:
                VelCov: [0.001, 0.001, 0.001, 0.001]
            - sensor_type: IMUSensor
              ros_publish: true
              tick_every: 3
              configuration:
                AccelCov: [0.001, 0.001, 0.001]
                AngVelCov: [0.001, 0.001, 0.001]
            - sensor_type: GPSSensor
              ros_publish: true
              tick_every: 30
              configuration:
                Cov: [0.0001, 0.0001, 0.0001]
                Depth: 1.5
                DepthCov: 0.05
            - sensor_type: LocationSensor
              ros_publish: true
            - sensor_type: RotationSensor
              ros_publish: true
            - sensor_type: DepthSensor
              tick_every: 5
              ros_publish: true
              configuration:
                Sigma: 0.001
            - sensor_type: VelocitySensor
              ros_publish: true
          
          