"""Plan a path with A* or RRT* and write it as an aircraft mission YAML.

    python3 to_mission.py scenarios/orchard.yaml --planner astar --out missions/plan_orchard_astar.yaml
    python3 to_mission.py scenarios/orchard.yaml --planner rrt   --seed 1

The mission is: takeoff to the start altitude, then for each remaining path
waypoint a go_to_known_gps_waypoint followed by wait_to_reach_waypoint (a 3D
arrival check; go_to_known_gps_waypoint alone advances as soon as the command
is sent), then land. A JSON with the path and planner metrics is written next
to it (make_world.py --path draws it in Gazebo).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import yaml

import astar
import rrt_star
from common import shortcut
from world import load_scenario

HERE = Path(__file__).resolve().parent
MISSIONS_DIR = HERE.parent / "missions"


def plan_scenario(sc, planner: str, resolution: float, rrt_iters: int, seed: int, smooth: bool):
    if planner == "astar":
        r = astar.plan(sc.world, sc.start, sc.goal, resolution=resolution)
    elif planner == "rrt":
        r = rrt_star.plan(sc.world, sc.start, sc.goal, max_iter=rrt_iters, seed=seed)
    else:
        raise ValueError(planner)
    if r.success and smooth:
        r.path = shortcut(r.path, sc.world)
    return r


def build_mission(path: np.ndarray, threshold: float, final_threshold: float, leg_timeout: float,
                  hover_s: float) -> dict:
    """path[0] is directly above home: takeoff reaches it, the rest are legs."""
    steps: list[dict] = [{"action": "takeoff", "params": {"takeoff_altitude": round(float(path[0][2]), 2)}}]
    for k, (n, e, u) in enumerate(path[1:], start=1):
        last = k == len(path) - 1
        wp = {"north": round(float(n), 2), "east": round(float(e), 2), "altitude": round(float(u), 2)}
        steps.append({"action": "go_to_known_gps_waypoint", "params": dict(wp)})
        steps.append({"action": "wait_to_reach_waypoint",
                      "params": {**wp, "threshold": final_threshold if last else threshold, "timeout": leg_timeout}})
    steps.append({"action": "wait", "params": {"duration": hover_s}})
    steps.append({"action": "land", "params": {"landing_altitude": 0.0, "vtol_transition_heading": 0.0}})
    return {"steps": steps}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("scenario")
    ap.add_argument("--planner", choices=["astar", "rrt"], required=True)
    ap.add_argument("--resolution", type=float, default=1.0, help="A* grid resolution (m)")
    ap.add_argument("--rrt-iters", type=int, default=5000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--no-smooth", action="store_true", help="fly the raw planner path, without shortcut smoothing")
    ap.add_argument("--threshold", type=float, default=1.5, help="waypoint arrival radius (m), fly-by")
    ap.add_argument("--final-threshold", type=float, default=0.75)
    ap.add_argument("--leg-timeout", type=float, default=90.0)
    ap.add_argument("--hover", type=float, default=5.0, help="seconds to hover at the goal before landing")
    ap.add_argument("--out")
    a = ap.parse_args()

    sc = load_scenario(a.scenario)
    r = plan_scenario(sc, a.planner, a.resolution, a.rrt_iters, a.seed, smooth=not a.no_smooth)
    if not r.success:
        raise SystemExit(f"{a.planner} found no path: {r.extra.get('reason')}")

    stem = f"plan_{sc.name}_{a.planner}"
    out = Path(a.out) if a.out else MISSIONS_DIR / f"{stem}.yaml"
    mission = build_mission(r.path, a.threshold, a.final_threshold, a.leg_timeout, a.hover)
    header = (f"# Generated by planning/to_mission.py -- scenario={sc.name} planner={a.planner} "
              f"length={sum(np.linalg.norm(np.diff(r.path, axis=0), axis=1)):.1f}m waypoints={len(r.path)}\n")
    out.write_text(header + yaml.safe_dump(mission, sort_keys=False))

    meta = out.with_suffix(".path.json")
    meta.write_text(json.dumps({
        "scenario": sc.name, "planner": a.planner, "seed": a.seed, "resolution": a.resolution,
        "smoothed": not a.no_smooth, "planning_time_s": r.time_s, "effort": r.effort,
        "path": r.path.tolist(),
    }, indent=1))
    print(f"{a.planner}: {len(r.path)} waypoints, planned in {r.time_s:.2f}s -> {out}\npath json -> {meta}")


if __name__ == "__main__":
    main()
